# Comprehensive NumPy Assignment

**Python for Data Science – NumPy Practice Assignment**

## Instructions
- Use only the NumPy library unless specified otherwise.
- Write clean and well-commented code.
- Display outputs for every question.
- Attempt all questions.
- Explain the logic behind your solutions wherever possible.

## Part 1: Introduction to NumPy

Q1. Import NumPy and display its version.

In [2]:
import numpy as np
np.__version__

'2.2.5'

Q2. Create arrays: (1) 1-D array from 1 to 10, (2) 3x4 zeros, (3) 3x3 ones, (4) identity matrix of size 5, (5) even numbers from 2 to 20.

In [3]:
import numpy as np

# 1. answer
arr1 = np.arange(1, 11)
print("1-D Array (1 to 10):")
print(arr1)

# 2.answer
arr2 = np.zeros((3, 4))
print("\n3x4 Zeros Matrix:")
print(arr2)

# 3. answer
arr3 = np.ones((3, 3))
print("\n3x3 Ones Matrix:")
print(arr3)

# 4. answer
arr4 = np.eye(5)
print("\n5x5 Identity Matrix:")
print(arr4)

# 5. answer
arr5 = np.arange(2, 21, 2)
print("\nEven Numbers (2 to 20):")
print(arr5)

1-D Array (1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]

3x4 Zeros Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

3x3 Ones Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Even Numbers (2 to 20):
[ 2  4  6  8 10 12 14 16 18 20]


Q3. Create arrays using np.arange(), np.linspace(), np.random.rand(), np.random.randint(), and np.full(). Explain the differences.

In [5]:
import numpy as np

# 1. answer
arr1 = np.arange(1, 11, 2)
print("Using np.arange():")
print(arr1)

# 2. answer
arr2 = np.linspace(0, 1, 5)
print("\nUsing np.linspace():")
print(arr2)

# 3. answer
arr3 = np.random.rand(3, 3)
print("\nUsing np.random.rand():")
print(arr3)

# 4. answer
arr4 = np.random.randint(1, 100, size=(3, 3))
print("\nUsing np.random.randint():")
print(arr4)

# 5. answer
arr5 = np.full((3, 4), 7)
print("\nUsing np.full():")
print(arr5)




Using np.arange():
[1 3 5 7 9]

Using np.linspace():
[0.   0.25 0.5  0.75 1.  ]

Using np.random.rand():
[[0.69596365 0.933487   0.10178292]
 [0.5744985  0.03043196 0.01735049]
 [0.48718118 0.37777329 0.47682741]]

Using np.random.randint():
[[95 11 28]
 [58 15 92]
 [65 72 45]]

Using np.full():
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
np.arange(start, stop, step)
Creates an array with evenly spaced values using a fixed step size.
Example: np.arange(1, 11, 2) → [1 3 5 7 9]
np.linspace(start, stop, num)
Creates an array with a specified number of equally spaced values between the start and stop values (inclusive).
Example: np.linspace(0, 1, 5) → [0.00 0.25 0.50 0.75 1.00]
np.random.rand(shape)
Generates random floating-point numbers between 0 and 1.
np.random.randint(low, high, size)
Generates random integers between low (inclusive) and high (exclusive).
np.full(shape, value)
Creates an array of the given shape with all elements set to the specified value.

## Array Attributes

Q4. Given arr = np.array([[10,20,30],[40,50,60],[70,80,90]]), find shape, size, dimension, dtype, itemsize, and memory occupied.

In [7]:

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])


print("Array:")
print(arr)

print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize, "bytes")
print("Memory Occupied:", arr.nbytes, "bytes")

Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Shape: (3, 3)
Size: 9
Dimension: 2
Data Type: int32
Item Size: 4 bytes
Memory Occupied: 36 bytes


Q5. Convert the array into float, integer, and boolean types.

In [9]:

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])


arr_float = arr.astype(float)
print("Float Array:")
print(arr_float)


arr_int = arr.astype(int)
print("\nInteger Array:")
print(arr_int)


arr_bool = arr.astype(bool)
print("\nBoolean Array:")
print(arr_bool)

Float Array:
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]

Integer Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Boolean Array:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Part 3: Indexing and Slicing

###### Creata a 4x4x2 array and display the elements, rows and columns

In [10]:
arr = np.arange(1, 33).reshape(4, 4, 2)


print("4x4x2 Array:")
print(arr)

# rows
print("\nRows:")
for i in range(arr.shape[0]):
    print(f"Row {i}:")
    print(arr[i])

# columns
print("\nColumns:")
for j in range(arr.shape[1]):
    print(f"Column {j}:")
    print(arr[:, j, :])


4x4x2 Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]]

Rows:
Row 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Row 1:
[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Row 2:
[[17 18]
 [19 20]
 [21 22]
 [23 24]]
Row 3:
[[25 26]
 [27 28]
 [29 30]
 [31 32]]

Columns:
Column 0:
[[ 1  2]
 [ 9 10]
 [17 18]
 [25 26]]
Column 1:
[[ 3  4]
 [11 12]
 [19 20]
 [27 28]]
Column 2:
[[ 5  6]
 [13 14]
 [21 22]
 [29 30]]
Column 3:
[[ 7  8]
 [15 16]
 [23 24]
 [31 32]]


Q7. Reverse the entire array, rows, and columns.

In [11]:


arr = np.arange(1, 33).reshape(4, 4, 2)

print("Original Array:")
print(arr)

# 1. Reverse array
reverse_entire = arr[::-1, ::-1, ::-1]
print("\nReversed Entire Array:")
print(reverse_entire)

# 2. Reverse rows
reverse_rows = arr[::-1, :, :]
print("\nRows Reversed:")
print(reverse_rows)

# 3. Reverse columns
reverse_columns = arr[:, ::-1, :]
print("\nColumns Reversed:")
print(reverse_columns)

Original Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]]

Reversed Entire Array:
[[[32 31]
  [30 29]
  [28 27]
  [26 25]]

 [[24 23]
  [22 21]
  [20 19]
  [18 17]]

 [[16 15]
  [14 13]
  [12 11]
  [10  9]]

 [[ 8  7]
  [ 6  5]
  [ 4  3]
  [ 2  1]]]

Rows Reversed:
[[[25 26]
  [27 28]
  [29 30]
  [31 32]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]]

Columns Reversed:
[[[ 7  8]
  [ 5  6]
  [ 3  4]
  [ 1  2]]

 [[15 16]
  [13 14]
  [11 12]
  [ 9 10]]

 [[23 24]
  [21 22]
  [19 20]
  [17 18]]

 [[31 32]
  [29 30]
  [27 28]
  [25 26]]]


Q8. Replace values greater than 30 with 0.

In [14]:
arr[arr> 30] = 0
print(f"array after replace: \n {arr}")

array after replace: 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [ 0  0]]]


## Part 4: Reshaping and Flattening

Q9. Create an array from 1 to 24 and reshape it into different dimensions. Compare flatten() and ravel().

In [15]:
arr = np.arange(1, 25, dtype = "int32")
arr = arr.reshape(4, 6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [16]:
arr = arr.reshape(3, 8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [17]:
arr = arr.flatten()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [18]:
arr = arr.ravel()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
1)flatten() returns a copy of the array as a 1-D array. Changes made to the flattened array do not affect the original array.
2)ravel() returns a view of the original array whenever possible. Changes made to the raveled array may affect the original array.

Q10. Demonstrate transpose(), swapaxes(), and reshape(-1).

In [19]:
arr = arr.reshape(3, 8)
arr_T = arr.T
print(f"transpose matrix: \n {arr_T}")

arr_swapaxes = np.swapaxes(arr, 0, 1)
print(f"array after swap axes: \n {arr_swapaxes}")

arr = arr.reshape(-1)
print(f"array after reshape (-1) (flatten the array in 1d): \n {arr}")

transpose matrix: 
 [[ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]
 [ 8 16 24]]
array after swap axes: 
 [[ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]
 [ 8 16 24]]
array after reshape (-1) (flatten the array in 1d): 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## Part 5: Mathematical Operations

Q11. Perform arithmetic operations between arrays.

In [21]:
import numpy as np


arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

# Addition
print("\nAddition:")
print(arr1 + arr2)

# Subtraction
print("\nSubtraction:")
print(arr1 - arr2)

# Multiplication
print("\nMultiplication:")
print(arr1 * arr2)

# Division
print("\nDivision:")
print(arr1 / arr2)

# Floor Division
print("\nFloor Division:")
print(arr1 // arr2)

# Modulus
print("\nModulus:")
print(arr1 % arr2)

# Power
print("\nPower:")
print(arr1 ** arr2)

Array 1:
[10 20 30 40 50]

Array 2:
[1 2 3 4 5]

Addition:
[11 22 33 44 55]

Subtraction:
[ 9 18 27 36 45]

Multiplication:
[ 10  40  90 160 250]

Division:
[10. 10. 10. 10. 10.]

Floor Division:
[10 10 10 10 10]

Modulus:
[0 0 0 0 0]

Power:
[       10       400     27000   2560000 312500000]


Q12. Find square root, exponential, logarithm, sine, cosine, and tangent values.

In [24]:

arr = np.array([1, 2, 3, 4, 5])

print("Original Array:")
print(arr)

# Square Root
print("\nSquare Root:")
print(np.sqrt(arr))

# Exponential
print("\nExponential:")
print(np.exp(arr))

# Natural Logarithm
print("\nLogarithm:")
print(np.log(arr))

# Sine
print("\nSine:")
print(np.sin(arr))

# Cosine
print("\nCosine:")
print(np.cos(arr))

# Tangent
print("\nTangent:")
print(np.tan(arr))

Original Array:
[1 2 3 4 5]

Square Root:
[1.         1.41421356 1.73205081 2.         2.23606798]

Exponential:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Logarithm:
[0.         0.69314718 1.09861229 1.38629436 1.60943791]

Sine:
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Cosine:
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]

Tangent:
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


Q13. Compare arrays using relational operators.

In [26]:

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([15, 20, 25, 40, 60])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

# Greater than
print("\narr1 > arr2:")
print(arr1 > arr2)

# Less than
print("\narr1 < arr2:")
print(arr1 < arr2)

# Greater than or equal to
print("\narr1 >= arr2:")
print(arr1 >= arr2)

# Less than or equal to
print("\narr1 <= arr2:")
print(arr1 <= arr2)

# Equal to
print("\narr1 == arr2:")
print(arr1 == arr2)

# Not equal to
print("\narr1 != arr2:")
print(arr1 != arr2)

Array 1:
[10 20 30 40 50]

Array 2:
[15 20 25 40 60]

arr1 > arr2:
[False False  True False False]

arr1 < arr2:
[ True False False False  True]

arr1 >= arr2:
[False  True  True  True False]

arr1 <= arr2:
[ True  True False  True  True]

arr1 == arr2:
[False  True False  True False]

arr1 != arr2:
[ True False  True False  True]


Q14. Perform Dot product of multi dimensional array

In [28]:

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10],
                 [11, 12]])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)


result = np.dot(arr1, arr2)

print("\nDot Product:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Dot Product:
[[ 58  64]
 [139 154]]


## Part 7: Aggregation Functions

Q15. Find sum, mean, median, standard deviation, variance, maximum, and minimum.

In [30]:

arr = np.array([10, 20, 30, 40, 50])

print("Array:")
print(arr)
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Array:
[10 20 30 40 50]

Sum: 150
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
Maximum: 50
Minimum: 10


Q16. Find row-wise and column-wise statistics.

In [59]:
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [61]:
np.var(arr[0]) # variance of first row

np.float64(125.0)

In [62]:
np.std(arr[:, 0]) # std of first column

np.float64(32.65986323710904)

Q17. Find cumulative sum and cumulative product.

In [53]:

cumsum = np.cumsum(arr)
print("\nCumulative Sum:")
print(cumsum)


cumprod = np.cumprod(arr)
print("\nCumulative Product:")
print(cumprod)


Cumulative Sum:
[ 1  3  6 10 15 21 28 36 45 55 66 78]

Cumulative Product:
[        1         2         6        24       120       720      5040
     40320    362880   3628800  39916800 479001600]


## Part 8: Sorting and Searching

Q18. Sort arrays and find indices and elements satisfying conditions.

In [50]:
sorted_arr = np.sort(arr)
print("Ascending Sort:", sorted_arr)


Ascending Sort: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [51]:
indices = np.where(sorted_arr > 5)
print("Indices where value > 5:", indices[0])

Indices where value > 5: [ 5  6  7  8  9 10 11]


Q19. Find unique elements and their frequencies.

In [64]:
arr = np.array([2, 3, 5, 2, 4, 3, 5, 6, 2, 7, 4, 5, 3])

print("Original Array:")
print(arr)
unique_elements = np.unique(arr)
print("\nUnique Elements:")
print(unique_elements)


unique, counts = np.unique(arr, return_counts=True)

print("\nUnique Elements with Frequencies:")
for i in range(len(unique)):
    print(f"{unique[i]} : {counts[i]}")
    

Original Array:
[2 3 5 2 4 3 5 6 2 7 4 5 3]

Unique Elements:
[2 3 4 5 6 7]

Unique Elements with Frequencies:
2 : 3
3 : 3
4 : 2
5 : 3
6 : 1
7 : 1


## Part 9: Stacking and Splitting

Q20. Demonstrate stacking methods.

In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [ ]:

np.vstack((a, b))

In [47]:

np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

Q21. Split arrays into equal parts.

In [49]:
matrix = np.arange(8).reshape(4, 2)
print(f"Original Matrix: \n {matrix}")

upper, lower = np.vsplit(matrix, 2)

print(f"Upper : \n {upper}")
print(f"Lower : \n {lower}")

Original Matrix: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Upper : 
 [[0 1]
 [2 3]]
Lower : 
 [[4 5]
 [6 7]]


## Part 10: Random Module

Q22. Generate random numbers and matrices.

In [43]:
matrix = np.random.rand(10).reshape(2, 5)
matrix

array([[0.83039554, 0.26207164, 0.61982568, 0.97013867, 0.83292798],
       [0.13399357, 0.02036409, 0.7218264 , 0.47037552, 0.43066371]])

Q23. Simulate rolling a die 100 times and analyze frequencies.

In [65]:
def roll():
    array = np.random.randint(1, 7, size=100)
    elements, counts = np.unique(array, return_counts=True)
    return elements, counts

elements, counts = roll()
for el, ct in zip(elements, counts):
    print(f"Number {el}: rolled {ct} times")

Number 1: rolled 19 times
Number 2: rolled 20 times
Number 3: rolled 9 times
Number 4: rolled 18 times
Number 5: rolled 21 times
Number 6: rolled 13 times


## Part 11: Boolean Masking and Filtering

Q24. Extract values based on conditions.

In [68]:
arr[arr > 1]

array([2, 3, 5, 2, 4, 3, 5, 6, 2, 7, 4, 5, 3])

Q25. Replace odd numbers with -1.

In [69]:
arr[arr % 2 != 0] = -1
arr

array([ 2, -1, -1,  2,  4, -1, -1,  6,  2, -1,  4, -1, -1])

## Part 12: Missing Values

Q26. Detect and replace missing values.

In [71]:
arr = np.array([1, 2, 3, 4,np.nan, 5])
np.isnan(arr)

array([False, False, False, False,  True, False])

## Part 13: Linear Algebra

Q27. Perform matrix operations.

In [76]:

A = np.arange(20).reshape(4, 5)
B = np.arange(20).reshape(5, 4)
C = np.arange(20).reshape(4, 5)
print(A.dot(B))
print(A + C)
print(A.T)

[[120 130 140 150]
 [320 355 390 425]
 [520 580 640 700]
 [720 805 890 975]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


Q28. Find determinant, inverse, transpose, eigenvalues, and eigenvectors.

In [77]:
A = np.random.rand(16).reshape(4, 4)
np.linalg.det(A)


np.float64(-0.023976199469366657)

In [78]:
np.linalg.inv(A)

array([[-0.78123742,  0.26869956,  3.39845945, -3.51166382],
       [-1.30326519, -5.3048879 ,  5.05210724,  0.42728858],
       [-0.58969473,  2.84715817, -2.22701173,  1.41225591],
       [ 1.56899083, -1.17857134, -0.07079585,  0.23410479]])

In [79]:
B.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [83]:
eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvectors

array([[-0.4578498 +0.j        ,  0.78291426+0.j        ,
         0.78291426-0.j        , -0.2073977 +0.j        ],
       [-0.45950103+0.j        , -0.10056172-0.30976885j,
        -0.10056172+0.30976885j, -0.87595125+0.j        ],
       [-0.61012742+0.j        , -0.07337642-0.2797422j ,
        -0.07337642+0.2797422j ,  0.42779509+0.j        ],
       [-0.45494714+0.j        , -0.18979517+0.40163896j,
        -0.18979517-0.40163896j, -0.08177388+0.j        ]])

Q29. Solve a system of linear equations using NumPy.

In [84]:
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 2]])
B = np.array([8, 13, 8])
solution = np.linalg.solve(A, B)
print(f"x = {solution[0]}")
print(f"y = {solution[1]}")
print(f"z = {solution[2]}")

x = 1.5555555555555558
y = 1.6666666666666667
z = 3.222222222222222


## Part 14: Advanced NumPy

Q30. Demonstrate fancy indexing, boolean indexing, where(), argmax(), argmin(), and argsort().

In [85]:

A[:, 0]

array([2, 1, 1])

In [88]:
A[A < 5]

array([2, 1, 1, 1, 3, 2, 1, 0, 2])

In [89]:

np.where(A > 10)

(array([], dtype=int32), array([], dtype=int32))

In [90]:
A.argmax(axis=0)

array([0, 1, 1])

In [92]:
A.argmin(axis=1)

array([1, 0, 1])

In [93]:
A.argsort(axis=0)

array([[1, 2, 0],
       [2, 0, 1],
       [0, 1, 2]])

Q31. Use tile(), repeat(), clip(), and diag().

In [94]:

print(f"A: \n {A}")
np.tile(A, reps=2)

A: 
 [[2 1 1]
 [1 3 2]
 [1 0 2]]


array([[2, 1, 1, 2, 1, 1],
       [1, 3, 2, 1, 3, 2],
       [1, 0, 2, 1, 0, 2]])

In [95]:
np.repeat(A, repeats=2)

array([2, 2, 1, 1, 1, 1, 1, 1, 3, 3, 2, 2, 1, 1, 0, 0, 2, 2])

In [96]:

np.clip(A)

array([[2, 1, 1],
       [1, 3, 2],
       [1, 0, 2]])

In [97]:
np.diag(A)

array([2, 3, 2])

Q32. Create a checkerboard pattern.

In [98]:
base_block = np.array([[0, 1],
                       [1, 0]])
checkerboard_tile = np.tile(base_block, (4, 4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q33. Write a line of code to extract the inner 2×2 submatrix (excluding the border rows and columns).

In [99]:
arr_3d = np.arange(32).reshape(2, 4, 4)
submatrix = arr_3d[:, 1:-1, 1:-1]
submatrix

array([[[ 5,  6],
        [ 9, 10]],

       [[21, 22],
        [25, 26]]])

Q34. Reshape a 1D array of 12 elements (from Step 4) into a 3×4 2D matrix.

In [102]:
arr_1d = np.arange(12)
arr_1d = arr_1d.reshape(3, 4)
arr_1d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Q35 Create a 3×3 identity matrix.

In [106]:
I = np.zeros((3, 3), dtype = "int32")
for i in range(len(I)):
    I[i][i] = 1
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Q35. Stack two identical 2×2 arrays of ones vertically.

In [107]:
I_1 = np.zeros((2, 2), dtype = "int32")
I_2 = np.zeros((2, 2), dtype = "int32")
for i in range(len(I_1)):
    I_1[i][i], I_2[i][i] = 1, 1
print(I_1)
print(I_2)

print(f"vertical stack: \n {np.vstack((I_1, I_2))}")

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
vertical stack: 
 [[1 0]
 [0 1]
 [1 0]
 [0 1]]


Q36. Create Matrix A with dimensions 2×3 and Matrix B with dimensions 3×2.

In [108]:
A = np.arange(6).reshape(2, 3)
B = np.arange(6).reshape(3, 2)

Q37. Perform a matrix multiplication (A × B) to yield a 2×2 matrix result.

In [109]:
A.dot(B)

array([[10, 13],
       [28, 40]])

# Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [111]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1,0,1])
y = np.zeros(x.shape)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j] = v[j] + x[i][j]
print(y)

[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]
