# Advanced NumPy Assignment — Smart Logistics Optimization System

In [3]:
import numpy as np
np.random.seed(42)

distance = np.random.uniform(1, 100, size=(500, 1000))
fuel_rate = np.random.uniform(0.08, 0.25, size=500)
weights = np.random.randint(1, 40, size=(500, 1000))
capacity = np.random.randint(5000, 12000, size=500)
delivery_time = np.random.normal(45, 12, size=(500, 1000))
fuel_price = np.random.uniform(85, 110, size=50)


## Task 1: Print shape, ndim, size, dtype for all datasets

In [4]:
print(distance.shape, distance.ndim, distance.size, distance.dtype)
print(fuel_rate.shape, fuel_rate.ndim, fuel_rate.size, fuel_rate.dtype)
print(weights.shape, weights.ndim, weights.size, weights.dtype)
print(capacity.shape, capacity.ndim, capacity.size, capacity.dtype)
print(delivery_time.shape, delivery_time.ndim, delivery_time.size, delivery_time.dtype)
print(fuel_price.shape, fuel_price.ndim, fuel_price.size, fuel_price.dtype)

(500, 1000) 2 500000 float64
(500,) 1 500 float64
(500, 1000) 2 500000 int32
(500,) 1 500 int32
(500, 1000) 2 500000 float64
(50,) 1 50 float64


## Task 2: Calculate total memory consumed by array

In [6]:
print(f"distance array consumed memory: {distance.nbytes}")
print(f"fuel_rate array consumed memory: {fuel_rate.nbytes}")
print(f"weights array consumed memory: {weights.nbytes}")
print(f"capacity array consumed memory: {capacity.nbytes}")
print(f"delivery_time array consumed memory: {delivery_time.nbytes}")
print(f"fuel_price array consumed memory: {fuel_price.nbytes}")

distance array consumed memory: 4000000
fuel_rate array consumed memory: 4000
weights array consumed memory: 2000000
capacity array consumed memory: 2000
delivery_time array consumed memory: 4000000
fuel_price array consumed memory: 400


## Part 2: Indexing & Slicing

*Extract:*

1. First 10 trucks
2. Last 50 deliveries of each truck
3. Every alternate delivery

Use slicing only.

In [11]:
first_10_trucks = distance[:10]
last_50_deliveries = distance[:, -50:]
alternate_deliveries = distance[:, ::2]

In [13]:
print(f"first 10 trucks: \n {first_10_trucks}")
print(f"last 50 trucks: \n {last_50_deliveries}")
print(f"alternate_deliveries: \n {alternate_deliveries}")

first 10 trucks: 
 [[38.07947177 95.12071633 73.46740024 ... 14.54504446 95.07349803
  45.15457152]
 [19.32815996 54.64819379 87.42163775 ...  7.82684362  6.64841739
  28.93652039]
 [26.90886269 25.45090111 90.71920347 ... 31.66899806 29.71450766
  87.26998938]
 ...
 [ 4.84114602 19.49048029 83.2933347  ... 46.07754623 90.93531724
  11.34355136]
 [72.30652447 69.04101744 10.47966567 ... 97.79356847 11.68453094
  93.26246983]
 [91.44422313 53.0106877  72.76611691 ... 94.72408359 40.35131125
  22.4969    ]]
last 50 trucks: 
 [[60.45116918 66.83863078 18.36175658 ... 14.54504446 95.07349803
  45.15457152]
 [ 9.77144254 22.84058332 60.22430411 ...  7.82684362  6.64841739
  28.93652039]
 [82.92312567 70.02372881 71.71833694 ... 31.66899806 29.71450766
  87.26998938]
 ...
 [77.08704768 79.35336583 12.36919284 ... 96.65204844 95.52891706
  69.72213447]
 [88.53282913 15.36861871 87.73662261 ... 63.01613795 48.96821262
  58.4720383 ]
 [90.81727575 39.72889623 92.2041779  ... 49.28635359 66.8336

1. Find trucks whose fuel rate exceeds 0.20.

In [14]:
print(np.where(fuel_rate > 0.20))

(array([  3,  10,  11,  15,  20,  24,  25,  34,  42,  44,  50,  56,  59,
        64,  73,  74,  82,  84,  95,  99, 106, 110, 111, 113, 114, 115,
       116, 117, 119, 122, 127, 135, 136, 137, 141, 143, 146, 149, 156,
       159, 160, 161, 163, 165, 168, 181, 191, 192, 203, 204, 207, 210,
       219, 223, 227, 228, 230, 232, 233, 235, 236, 239, 241, 242, 244,
       245, 246, 248, 255, 256, 258, 264, 268, 271, 274, 276, 279, 284,
       301, 304, 305, 306, 309, 314, 321, 325, 327, 328, 329, 330, 340,
       341, 343, 345, 347, 348, 354, 355, 357, 358, 363, 364, 366, 369,
       374, 377, 378, 382, 384, 385, 388, 392, 393, 395, 397, 411, 414,
       418, 423, 424, 425, 426, 427, 430, 433, 440, 442, 444, 445, 446,
       451, 452, 454, 456, 458, 461, 466, 472, 475, 478, 479, 480, 485,
       487, 489, 492, 495, 497, 498]),)


*Find deliveries where:*

* Distance > 80 km
* Weight > 30 kg

Return their indices.

In [16]:
print(np.where((distance > 80) & (weights > 30)))

(array([  0,   0,   0, ..., 499, 499, 499], shape=(23319,)), array([  1,   7,  35, ..., 852, 991, 996], shape=(23319,)))


## Task 3: Extract slices

In [19]:
task3_first_10_trucks = [
    distance[:10, :],
    fuel_rate[:10],
    weights[:10, :],
    capacity[:10],
    delivery_time[:10, :],
    fuel_price[:10]
]

task3_last_50_deliveries_per_truck = [
    distance[:, -50:],
    weights[:, -50:],
    delivery_time[:, -50:]
]

task3_alternate_deliveries = [
    distance[:, ::2],
    fuel_rate[::2],
    weights[:, ::2],
    capacity[::2],
    delivery_time[:, ::2],
    fuel_price[::2]
]

print("first 10 trucks (example distance slice shape):", task3_first_10_trucks[0].shape)
print("last 50 deliveries per truck (example distance slice shape):", task3_last_50_deliveries_per_truck[0].shape)
print("alternate deliveries (example distance slice shape):", task3_alternate_deliveries[0].shape)

first 10 trucks (example distance slice shape): (10, 1000)
last 50 deliveries per truck (example distance slice shape): (500, 50)
alternate deliveries (example distance slice shape): (500, 500)


## Task 4: Boolean indexing on fuel_rate > 0.20

In [21]:
print(np.where(fuel_rate > 0.20)[0])

[  3  10  11  15  20  24  25  34  42  44  50  56  59  64  73  74  82  84
  95  99 106 110 111 113 114 115 116 117 119 122 127 135 136 137 141 143
 146 149 156 159 160 161 163 165 168 181 191 192 203 204 207 210 219 223
 227 228 230 232 233 235 236 239 241 242 244 245 246 248 255 256 258 264
 268 271 274 276 279 284 301 304 305 306 309 314 321 325 327 328 329 330
 340 341 343 345 347 348 354 355 357 358 363 364 366 369 374 377 378 382
 384 385 388 392 393 395 397 411 414 418 423 424 425 426 427 430 433 440
 442 444 445 446 451 452 454 456 458 461 466 472 475 478 479 480 485 487
 489 492 495 497 498]


## Task 5: Find deliveries with distance>80 and weight>30

In [22]:
deliveries_task5 = np.where((distance > 80) & (weights > 30))

print("Truck indices:")
print(deliveries_task5[0])

print("Delivery indices:")
print(deliveries_task5[1])

Truck indices:
[  0   0   0 ... 499 499 499]
Delivery indices:
[  1   7  35 ... 852 991 996]


# Task 6: Broadcasting

* Compute total fuel consumed per delivery.

        Formula:

            fuel=distance×fuel_rate

In [26]:
total_fuel_consumed = distance * fuel_rate[:, np.newaxis]

print("Shape of distance:", distance.shape)
print("Shape of fuel_rate:", fuel_rate.shape)
print("Shape of total fuel consumed:", total_fuel_consumed.shape)
print("First 10 fuel values for first truck:")
print(total_fuel_consumed[0, :10])

Shape of distance: (500, 1000)
Shape of fuel_rate: (500,)
Shape of total fuel consumed: (500, 1000)
First 5 fuel values for first truck:
[ 4.98265018 12.44642408  9.61311536  7.88588473  2.15191784  2.15160539
  0.88326519 11.35131477  7.91770664  9.30323745]



* Calculate fuel cost per delivery.

        Formula:

        cost=fuel×city_fuel_price

Challenge: Map 500 trucks to 50 warehouses.

In [28]:
truck_fuel_price = np.repeat(fuel_price, 10)

fuel_cost = total_fuel_consumed * truck_fuel_price[:, np.newaxis]

print("Fuel cost array shape (500 trucks × 1000 deliveries):", fuel_cost.shape)
print("Fuel cost of the first 5 deliveries for Truck 1:")
print(fuel_cost[0, :5])

Fuel cost array shape (500 trucks × 1000 deliveries): (500, 1000)
Fuel cost of the first 5 deliveries for Truck 1:
[ 546.47770694 1365.07542081 1054.3291321   864.8931887   236.01398518]


* Calculate total distance traveled per truck.

In [29]:
total_distance_per_truck = np.sum(distance, axis=1)

print("Total distance traveled by each truck:")
print(total_distance_per_truck)

Total distance traveled by each truck:
[49535.39877869 51194.71321274 50738.16688426 49547.12973096
 49916.42693361 50347.98442967 49837.5750871  48754.69114491
 49163.1725126  50182.70339291 51063.4822607  51019.90319215
 50244.02430705 49868.85162429 50984.39010227 49608.13561554
 51700.2427023  51411.46454539 52641.91544691 50942.16811713
 51885.02724907 50700.60406295 53240.93629018 50775.1525104
 50242.95153472 50610.57880658 49480.75314631 49742.27255204
 49038.2468435  49333.36763744 50865.51423916 51048.87746998
 50452.74243758 49816.8999217  50620.04682087 49465.96017392
 49753.21129849 51027.3051528  50980.58230392 49695.10937813
 50440.75371784 50860.52628537 50878.14085862 49519.97102026
 50036.40702199 50882.52260429 49928.16498405 50681.802159
 48703.43621264 49963.44262429 51421.80075876 51596.46467778
 50196.99649333 50222.93667106 51119.85622444 50490.32436576
 52014.59452049 50201.66023704 50674.12904582 50174.38027112
 49483.46410696 50774.11988807 51705.07488998 499

* Calculate average delivery time per truck.

In [30]:
average_delivery_time_per_truck = np.mean(delivery_time, axis=1)

print("Average delivery time for each truck (in minutes):")
print(average_delivery_time_per_truck)

Average delivery time for each truck (in minutes):
[45.21809592 45.0722776  45.13777291 44.47015878 45.03155726 45.38503285
 45.5052486  44.70365861 44.68514431 45.21451363 45.25102215 44.45205466
 45.55561011 45.12196771 44.97831623 44.98422544 45.56600548 44.76558723
 44.34414946 45.56885272 45.03299658 45.27692571 45.06427815 45.04220799
 44.37096545 45.16153966 44.91357903 44.41828458 44.98654026 44.52861047
 44.3675297  44.73546031 45.09265992 45.02429026 44.24547812 45.63309721
 44.31168811 44.26067057 45.62178927 44.3660236  45.45169193 44.61092958
 45.17454753 45.33665304 45.16895553 45.17002518 45.06492381 45.0565903
 44.99503405 45.11870543 45.27932511 45.08426956 44.35900383 45.10365715
 44.3459397  44.83974723 44.79880114 44.14422811 45.10319834 45.33457058
 45.20629498 45.19027685 44.85211964 44.55943149 44.86320443 45.33396918
 45.19380349 44.65659349 44.82907599 45.16280523 45.20296354 45.08530414
 45.22438505 45.13723106 44.18360191 45.43575075 44.35649821 44.37107982
 

* Calculate efficiency score:

    Efficiency=TotalWeightDelivered/FuelConsumed

Rank top 20 trucks.

In [31]:
total_weight_delivered = np.sum(weights, axis=1)
total_fuel_consumed_per_truck = np.sum(total_fuel_consumed, axis=1)

efficiency = total_weight_delivered / total_fuel_consumed_per_truck

top_20_trucks = np.argsort(efficiency)[-20:][::-1]

print("Top 20 most efficient truck indices:")
print(top_20_trucks)

print("Efficiency scores of top 20 trucks:")
print(efficiency[top_20_trucks])

Top 20 most efficient truck indices:
[ 13 307 112 251 164 428 118  85  39 155  35 316  27 413 121 182  62 202
 365 134]
Efficiency scores of top 20 trucks:
[5.02004852 4.8993169  4.88850106 4.86125607 4.73132756 4.70932279
 4.6065633  4.60380719 4.58897087 4.56332908 4.56200508 4.54779233
 4.53926508 4.50558668 4.49665194 4.46246457 4.39377832 4.39252197
 4.38242054 4.37215502]


### Compute:

    * mean
    * median
    * std
    * variance
    * min
    * max

For:

    * distance
    * weights
    * delivery_time

In [32]:
print("Distance:")
print("Mean:", np.mean(distance))
print("Median:", np.median(distance))
print("Standard Deviation:", np.std(distance))
print("Variance:", np.var(distance))
print("Minimum:", np.min(distance))
print("Maximum:", np.max(distance))

print("\nWeights:")
print("Mean:", np.mean(weights))
print("Median:", np.median(weights))
print("Standard Deviation:", np.std(weights))
print("Variance:", np.var(weights))
print("Minimum:", np.min(weights))
print("Maximum:", np.max(weights))

print("\nDelivery Time:")
print("Mean:", np.mean(delivery_time))
print("Median:", np.median(delivery_time))
print("Standard Deviation:", np.std(delivery_time))
print("Variance:", np.var(delivery_time))
print("Minimum:", np.min(delivery_time))
print("Maximum:", np.max(delivery_time))

Distance:
Mean: 50.52807875474377
Median: 50.59150316683937
Standard Deviation: 28.566154319826524
Variance: 816.0251726241436
Minimum: 1.000220502275013
Maximum: 99.9998331712345

Weights:
Mean: 19.962984
Median: 20.0
Standard Deviation: 11.25905528078373
Variance: 126.766325815744
Minimum: 1
Maximum: 39

Delivery Time:
Mean: 44.979109984264426
Median: 45.00448121768771
Standard Deviation: 12.003248144250556
Variance: 144.0779660124544
Minimum: -12.39886890779367
Maximum: 99.98411491369484


Find percentile statistics:

    25th
    50th
    75th
    90th
    99th

In [33]:
print("Distance Percentiles:")
print("25th:", np.percentile(distance, 25))
print("50th:", np.percentile(distance, 50))
print("75th:", np.percentile(distance, 75))
print("90th:", np.percentile(distance, 90))
print("99th:", np.percentile(distance, 99))

print("\nWeights Percentiles:")
print("25th:", np.percentile(weights, 25))
print("50th:", np.percentile(weights, 50))
print("75th:", np.percentile(weights, 75))
print("90th:", np.percentile(weights, 90))
print("99th:", np.percentile(weights, 99))

print("\nDelivery Time Percentiles:")
print("25th:", np.percentile(delivery_time, 25))
print("50th:", np.percentile(delivery_time, 50))
print("75th:", np.percentile(delivery_time, 75))
print("90th:", np.percentile(delivery_time, 90))
print("99th:", np.percentile(delivery_time, 99))

Distance Percentiles:
25th: 25.75673061477656
50th: 50.59150316683937
75th: 75.23774456143124
90th: 90.05937271623232
99th: 98.9960091170328

Weights Percentiles:
25th: 10.0
50th: 20.0
75th: 30.0
90th: 36.0
99th: 39.0

Delivery Time Percentiles:
25th: 36.88965814594672
50th: 45.00448121768771
75th: 53.051593478412414
90th: 60.35696838648573
99th: 72.94812050267876


Task 

    Reshape distance matrix into daily batches.

Assume:

    1000 deliveries = 20 days × 50 deliveries/day

In [34]:
daily_distance = distance.reshape(500, 20, 50)

print("Shape of daily distance array (Trucks × Days × Deliveries):")
print(daily_distance.shape)

Shape of daily distance array (Trucks × Days × Deliveries):
(500, 20, 50)


Compute per-day metrics:

    daily distance
    daily weight
    daily delivery time

Aggregate across axis.

In [37]:
daily_distance = distance.reshape(500, 20, 50)
daily_weight = weights.reshape(500, 20, 50)
daily_delivery_time = delivery_time.reshape(500, 20, 50)

daily_distance_total = np.sum(daily_distance, axis=2)
daily_weight_total = np.sum(daily_weight, axis=2)
daily_delivery_time_avg = np.mean(daily_delivery_time, axis=2)

print("Daily total distance shape:", daily_distance_total.shape)
print("Daily total weight shape:", daily_weight_total.shape)
print("Daily average delivery time shape:", daily_delivery_time_avg.shape)

Daily total distance shape: (500, 20)
Daily total weight shape: (500, 20)
Daily average delivery time shape: (500, 20)


Flatten reshaped array back.

Use:

    reshape()
    flatten()
    ravel()

In [38]:

distance_reshape = daily_distance.reshape(500, 1000)
distance_flatten = daily_distance.flatten()
distance_ravel = daily_distance.ravel()

print("Reshaped array shape:", distance_reshape.shape)
print("Flattened array shape:", distance_flatten.shape)
print("Ravel array shape:", distance_ravel.shape)

Reshaped array shape: (500, 1000)
Flattened array shape: (500000,)
Ravel array shape: (500000,)


Identify overloaded trucks.

Condition:

    TotalWeight>Capacity

    Return truck IDs.

In [39]:
total_weight = np.sum(weights, axis=1)

overloaded_trucks = np.where(total_weight > capacity)[0]

print("Overloaded Truck IDs:")
print(overloaded_trucks)

Overloaded Truck IDs:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 

Find critical deliveries:

Conditions:

    distance > 90
    delivery_time > 70
    weight > 35

Use combined masks.

In [40]:
critical_deliveries = np.where(
    (distance > 90) &
    (delivery_time > 70) &
    (weights > 35)
)

print("Truck IDs:")
print(critical_deliveries[0])

print("Delivery IDs:")
print(critical_deliveries[1])

Truck IDs:
[  0   6  12  14  15  19  21  22  24  25  35  42  43  49  53  55  56  60
  69  72  82  92  92 103 103 119 121 131 135 145 146 147 148 150 151 163
 164 164 167 170 170 172 177 177 183 184 188 188 190 195 205 214 219 221
 226 228 237 237 240 243 249 253 263 272 274 278 291 292 293 304 316 324
 328 328 346 346 361 375 389 391 394 394 401 402 407 410 413 414 415 424
 431 440 440 441 447 450 453 462 469 473 488 491 499]
Delivery IDs:
[661 358 767  61 131 171 312 633  29 417 565 602 698 390  39 420 363 661
 318 939 269 781 984 495 599 768 318 960 981 959 575 322 638 178  73 183
 283 829 211 225 874 859 501 777 455 835 881 920 384 932  73 144 233 584
 461 599 552 911 285 122 949 648 222  43 747 712 139  20 147 454 983 507
 114 931 125 526 583 581 704 376 118 622 626 656 492 610 534 688 715 310
 688  89 602 602 818 935   0 687 269 877 268 883 133]


Compare execution time:

Method 1:
    Python loop

Method 2:
    NumPy vectorized

In [46]:
# Method 1: Python loop
import time

start = time.time()

fuel_loop = []
for i in range(500):
    fuel_loop.append(distance[i] * fuel_rate[i])

end = time.time()
print("Python loop execution time:", end - start, "seconds")


Python loop execution time: 0.003000020980834961 seconds


In [47]:
# Method 2: NumPy vectorized
start = time.time()

fuel_vectorized = distance * fuel_rate[:, np.newaxis]

end = time.time()
print("NumPy vectorized execution time:", end - start, "seconds")

NumPy vectorized execution time: 0.002000093460083008 seconds


Create a Truck Risk Score.

    Formula:

Risk=0.35(overload ratio)+0.25(avg delay)+0.25(fuel inefficiency)+0.15(failure probability)

In [48]:
overload_ratio = total_weight / capacity
avg_delay = np.mean(delivery_time, axis=1)
fuel_inefficiency = np.sum(total_fuel_consumed, axis=1)
failure_probability = fuel_rate

risk_score = (0.35 * overload_ratio) + \
             (0.25 * avg_delay) + \
             (0.25 * fuel_inefficiency) + \
             (0.15 * failure_probability)

print("Truck Risk Score:")
print(risk_score)

Truck Risk Score:
[1632.42548665 2144.43878434 2415.36963726 3092.5997999  2485.46464894
 2043.1886383  1863.14171249 1619.44298101 1360.44725895 1652.35711959
 2722.68575912 3043.1860366  2173.22818829 1031.52467028 1484.94495225
 2637.74230226 1187.1873839  2486.85821809 1601.80766347 2444.74778125
 3024.03533553 2150.89194666 1229.85230391 1890.39471084 3039.19705374
 2942.66884397 2407.66522196 1118.70535657 1537.99315055 2026.93268612
 2001.49486077 1435.59241573 1242.59313798 1546.40258045 2700.77238941
 1114.20275717 1850.09613672 1922.70753539 2449.13644401 1094.56480945
 1670.27255649 1806.66529974 2783.39613247 1775.53531779 2668.10103415
 2516.26005901 2418.58171945 1812.37801785 1439.45204456 2431.3859289
 3059.99151482 1864.37396037 1441.2936855  2272.63385233 1855.93311335
 1329.3662409  2747.24076299 1809.59765201 2224.28515883 2888.65068827
 1876.30125218 2154.44266673 1170.13269623 1860.6587374  3077.30683277
 2179.93551514 2394.70032222 2030.76246107 2089.53809027 118

Implement mini NumPy functions manually:

Create your own version of:

    mean
    std
    normalization

Without using NumPy built-ins.

In [52]:
def my_mean(arr):
    flat_arr = arr.flatten() if hasattr(arr, 'flatten') else np.array(arr).flatten()
    total_sum = 0
    for x in flat_arr:
        total_sum += x
    return total_sum / len(flat_arr)

def my_std(arr):
    flat_arr = arr.flatten() if hasattr(arr, 'flatten') else np.array(arr).flatten()
    mean_val = custom_mean(flat_arr)
    sum_sq_diff = 0
    for x in flat_arr:
        sum_sq_diff += (x - mean_val)**2
    variance = sum_sq_diff / len(flat_arr)
    return variance**0.5

def my_normalize(arr):
    flat_arr = arr.flatten() if hasattr(arr, 'flatten') else np.array(arr).flatten()
    min_val = flat_arr[0]
    max_val = flat_arr[0]
    for x in flat_arr:
        if x < min_val:
            min_val = x
        if x > max_val:
            max_val = x

    if max_val == min_val:
        return np.zeros_like(arr, dtype=float)

    normalized_arr = (arr - min_val) / (max_val - min_val)
    return normalized_arr


print(f"original distance mean (NumPy): {np.mean(distance):.2f}")
print(f"custom mean of distance: {my_mean(distance):.2f}")

print(f"original distance std (NumPy): {np.std(distance):.2f}")
print(f"custom std of distance: {my_std(distance):.2f}")

original distance mean (NumPy): 50.53
custom mean of distance: 50.53
original distance std (NumPy): 28.57
custom std of distance: 28.57
